language: php
sudo: false

php:
  - 5.3

env:
  - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=3.2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=3
    - php: 5.6 
      env: DB=PGSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=master
  allow_failures:
    - env: DB=PGSQL CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - tar cf ~/gitbackup.tar .git
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: ./silvershop/tests/travis/run_build.sh

after_success: ./silvershop/tests/travis/upload_coverage.sh

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
