language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION=3.0.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1

before_script:
 # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2.0 --no-update; fi
  - composer update

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
#  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
