---
Name: shopconfig
After: framework/routes#coreroutes
---
ShopConfig:
  base_currency: 'NZD'

Product_Image:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 600

Injector:
  CheckoutComponentConfig:
    class: SinglePageCheckoutComponentConfig
